### PR TITLE
Fixed warning messages + Updated training documents + Added missing 'Makefile'

### PR DESCRIPTION
**Pull request by LindaMongMCHP**
1. Fixed warning messages
    - 'printWarningMessageForGlobalArrayReset' warnings from SmartHLS
       - continued Stefan's effort at commit https://github.com/MicrochipTech/fpga-hls-examples/commit/a4537bd81f065070e17a4356308c30e6e4417e4f.
       - commit https://github.com/MicrochipTech/fpga-hls-examples/commit/df3532c04954096d0af3e4ff3b888cb7fb132137 fixed Training1 pipeline_hazards at source code, and leave the rest untouched with explanation on documents in commit https://github.com/MicrochipTech/fpga-hls-examples/commit/df3532c04954096d0af3e4ff3b888cb7fb132137.
   - warning messages from llvm and gcc
       - commit https://github.com/MicrochipTech/fpga-hls-examples/commit/fa4df026ec890b325382ae1fb26a2b88edea6bad fixed 'missing-braces' warnings in Training 2 digit_recognition* examples and 'unused-variable' warning generated from SmartHLS generated code.
       - commit https://github.com/MicrochipTech/fpga-hls-examples/commit/a3f58c7518a8055b22f8ac9a100721f73ac9ad81 fixed warning messages in <axi_initiator>, <axi_target> and <udp_tx>.
       - commit https://github.com/MicrochipTech/fpga-hls-examples/commit/2bbb4f7d83c97537617c7f2a694a59e1f312281b fixed gcc warning messages in Training1 Canny* examples.

2. Updated training/tutorial documents (commit https://github.com/MicrochipTech/fpga-hls-examples/commit/407ebf8b44c9bc8e8cb5e2e3ed8573c4df743bda)
   - documents updated to match Windows version of SmartHLS/Libero 2022.2; includes outdated figures updates, experimental results correction and reference links updated or fixed

4. Added missing 'Makefile' (https://github.com/MicrochipTech/fpga-hls-examples/commit/73c8f63af1b382d49bfc482d1ca676694713ef0c, https://github.com/MicrochipTech/fpga-hls-examples/commit/df3532c04954096d0af3e4ff3b888cb7fb132137, https://github.com/MicrochipTech/fpga-hls-examples/commit/a3f58c7518a8055b22f8ac9a100721f73ac9ad81)
   - all examples contain 'Makefile' and 'config.tcl', so always the same compilation configurations are used 
   - commit https://github.com/MicrochipTech/fpga-hls-examples/commit/73c8f63af1b382d49bfc482d1ca676694713ef0c also updated and renamed the old 'makefile' as 'Makefile' in Training1 examples. Notice '**makefile**' is always silently overwritten by automatically generated content in Windows version of SmartHLS while '**Makefile**' will stay untouched.
   - legup's examples/github_example/Training*.exp have been updated to skip 'shls init' to avoid overwritting 'Makefile' (at [commit fe3b..2f57](https://bitbucket.microchip.com/projects/HLS/repos/legup/commits/fe3bc172cd4f5659a9d928fee4ec083f2f5716eb))

**Have passed [BuildBot tests](http://10.245.245.162:16000/builders/D_develop_linda/builds/12)!**

### CODE REVIEW

**Comment by SHLegupMCHP** [comment]
Did the "Synthesize Hardware to FPGA" icon change for the Sobel PDF on pg. 24 and 29? It shows up as a pointing hand for me now instead of the FPGA icon.

**Comment by LindaMongMCHP** [comment]
Thanks! I notice the same. I didn't touch icon pictures in this update, interesting! Will fix it now

**Comment by LindaMongMCHP** [comment]
Icons fixed in sobel tutorial, new commit pushed

**Comment by LindaMongMCHP** [comment]
https://github.com/MicrochipTech/fpga-hls-examples/commit/0f5eedd01f233de284b91a1bbd7187dbf81e3ff8 : 'Figure 12' reference fixed in Training 1 document

**Review by SHLegupMCHP — APPROVED** [review]
Everything looks good, thanks for making all these corrections in the documents and fixing all the warnings, especially all those ones in the test_images.

**Pull request merged**
